name: Enforce Commit Message

on:
  push:
    branches:
      - '**'

jobs:
  enforce-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Commit Message
        run: |
          commit_message=$(git log -1 --pretty=format:"%s")
          ticket_pattern="[A-Z]+-[0-9]+"

          if [[ ! $commit_message =~ $ticket_pattern ]]; then
            echo "Error: Commit message must include a ticket number (e.g., ABC-123)."
            exit 1
          fi
